export const templates: Template[] = [
  {
    id: "business-landing-1",
    title: "Business Landing Pro",
    description:
      "A professional landing page template for businesses and startups.",
    category: "Business",
    price: 49.99,
    rating: 4.8,
    reviews: 124,
    sales: 1250,
    thumbnail:
      "/placeholder.svg?height=450&width=800&text=Business Landing Pro",
    featured: true,
    isNew: false,
  },
  {
    id: "saas-website-1",
    title: "SaaS Platform UI",
    description:
      "Modern UI template for SaaS products with dashboard and landing pages.",
    category: "SaaS",
    price: 79.99,
    rating: 4.9,
    reviews: 87,
    sales: 980,
    thumbnail: "/placeholder.svg?height=450&width=800&text=SaaS Platform UI",
    featured: true,
    isNew: true,
  },
  {
    id: "ecommerce-store-1",
    title: "E-Commerce Complete",
    description:
      "Full-featured e-commerce template with product listings, cart, and checkout.",
    category: "E-Commerce",
    price: 99.99,
    rating: 4.7,
    reviews: 156,
    sales: 1450,
    thumbnail: "/placeholder.svg?height=450&width=800&text=E-Commerce Complete",
    featured: true,
    isNew: false,
  },
  {
    id: "portfolio-minimal-1",
    title: "Portfolio Minimal",
    description:
      "Clean and minimal portfolio template for creatives and designers.",
    category: "Portfolio",
    price: 39.99,
    rating: 4.6,
    reviews: 92,
    sales: 870,
    thumbnail: "/placeholder.svg?height=450&width=800&text=Portfolio Minimal",
    featured: false,
    isNew: false,
  },
  {
    id: "blog-magazine-1",
    title: "Blog & Magazine",
    description:
      "Modern blog and magazine template with multiple layouts and article pages.",
    category: "Blog",
    price: 59.99,
    rating: 4.5,
    reviews: 78,
    sales: 650,
    thumbnail: "/placeholder.svg?height=450&width=800&text=Blog & Magazine",
    featured: false,
    isNew: true,
  },
  {
    id: "event-conference-1",
    title: "Event & Conference",
    description:
      "Template for events, conferences, and meetups with schedule and speaker sections.",
    category: "Events",
    price: 69.99,
    rating: 4.7,
    reviews: 64,
    sales: 520,
    thumbnail: "/placeholder.svg?height=450&width=800&text=Event & Conference",
    featured: true,
    isNew: false,
  },
  {
    id: "restaurant-cafe-1",
    title: "Restaurant & Cafe",
    description:
      "Elegant template for restaurants, cafes, and food businesses with menu and reservation features.",
    category: "Food & Beverage",
    price: 54.99,
    rating: 4.8,
    reviews: 112,
    sales: 980,
    thumbnail: "/placeholder.svg?height=450&width=800&text=Restaurant & Cafe",
    featured: false,
    isNew: false,
  },
  {
    id: "real-estate-1",
    title: "Real Estate Pro",
    description:
      "Complete real estate template with property listings, search, and agent profiles.",
    category: "Real Estate",
    price: 89.99,
    rating: 4.6,
    reviews: 95,
    sales: 760,
    thumbnail: "/placeholder.svg?height=450&width=800&text=Real Estate Pro",
    featured: false,
    isNew: true,
  },
];
