export const templates: Template[] = [
  {
    id: "business-landing-1",
    title: "Business Landing Pro",
    description:
      "A professional landing page template for businesses and startups.",
    category: "Business",
    price: 49.99,
    rating: 4.8,
    reviews: 124,
    sales: 1250,
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1CDFAhOqze7uyc8TLI8BrO0epC7kbVmUB",
    images: [
      "https://drive.google.com/uc?export=view&id=1gdglY4uYbiRsbxVQLPlgKdhpzqdIw7OE",
      "https://drive.google.com/uc?export=view&id=1AMpEKPiCKbVvxazt70PKgFX8pCFGqH6N",
      "https://drive.google.com/uc?export=view&id=1Kus3L_2YuTbHdliAhQ61_oCvMa87Fa-7",
      "https://drive.google.com/uc?export=view&id=11quVTGnt66dKgspw-r9Ge3W4GfjXvRU8",
    ],
    demoUrl: "https://business-demo1.vercel.app",
    featured: true,
    isNew: false,
  },
  {
    id: "business-landing-2",
    title: "Business Landing Pro",
    description:
      "A professional landing page template for businesses and startups.",
    category: "Business",
    price: 49.99,
    rating: 4.8,
    reviews: 124,
    sales: 1250,
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1MCwMK0WpovBPb1Pp8TUEg9MvrhNQXpdA",

    images: [
      "https://drive.google.com/uc?export=view&id=12cFA0RjJhC0aXwGZTaj1VM_6QC9eSppl",
      "https://drive.google.com/uc?export=view&id=1rFxzFgFNrydfaL2QVSZvHNQlzeQm3mJu",
      "https://drive.google.com/uc?export=view&id=1Xbetpkn4FfkRH8xM4Q3WUb-QNhzv6pZg",
      "https://drive.google.com/uc?export=view&id=1Bz7IQCpwAv9ptNoFLqVE_mUPGgh1Ko_Y",
      "https://drive.google.com/uc?export=view&id=1iwNlMZQHP57rMpCPGHV98k8KeWKvosZP",
      "https://drive.google.com/uc?export=view&id=14vVSCVlgqeZSX3VlG583_YHyMVVLDO3j",
    ],
    demoUrl: "https://business-demo2.vercel.app",
    featured: true,
    isNew: false,
  },
  {
    id: "business-landing-3",
    title: "Business Landing Pro",
    description:
      "A professional landing page template for businesses and startups.",
    category: "Business",
    price: 49.99,
    rating: 4.8,
    reviews: 124,
    sales: 1250,
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1ZpEpTHNqztuUOKmfGQ0UH9mad57BvEt1",
    images: [
      "https://drive.google.com/uc?export=view&id=1tzS1yrjlSCgNk89OuOCbNDoi4hzKLVuc",
      "https://drive.google.com/uc?export=view&id=1KY4BKq1r5uQlECmO0UToX1bwqz9Ptnnj",
      "https://drive.google.com/uc?export=view&id=1W3sZQOVvdJRAG2Zb1HJe4QdgEQPlDQOt",
      "https://drive.google.com/uc?export=view&id=16avXXcUKAN9d1_kd6jltJvnG66RibAFi",
      "https://drive.google.com/uc?export=view&id=1CHaaCeq12h90o82xhlDekj2-s7EfNXYp",
      "https://drive.google.com/uc?export=view&id=15fD1ztzTbQD1wGBDxNEPa3Xtbn5LlIce",
      "https://drive.google.com/uc?export=view&id=1dfl9-wxVkrau8n3x-GCoh76Ycn2T7ngZ",
    ],
    demoUrl: "https://business-demo3.vercel.app",
    featured: true,
    isNew: false,
  },
  {
    id: "business-landing-4",
    title: "Business Landing Pro",
    description:
      "A professional landing page template for businesses and startups.",
    category: "Business",
    price: 49.99,
    rating: 4.8,
    reviews: 124,
    sales: 1250,
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1CNhYIk6k6chWAw_xazhNwBZBtlwYUhpM",
    images: [
      "https://drive.google.com/uc?export=view&id=1vPYNRDAkh8MQ6q1f61FGhcrIx4Sp4XQd",
      "https://drive.google.com/uc?export=view&id=1fyUUmxBAWzqCTfKIP-n6FVH9SoW8qvul",
      "https://drive.google.com/uc?export=view&id=14e-_TO-blCqNU0Jvw9zGgCJ-nLcqqc6H",
      "https://drive.google.com/uc?export=view&id=1_Cd9O91oQB-2n6JOR4cbCP5zJmzv3zYQ",
      "https://drive.google.com/uc?export=view&id=1bKu9VTJigjKtRYEnlkH-5Tgvfkjmh_f2",
    ],
    demoUrl: "https://business-demo4.vercel.app",
    featured: true,
    isNew: false,
  },
  {
    id: "saas-website-1",
    title: "SaaS Platform UI",
    description:
      "Modern UI template for SaaS products with dashboard and landing pages.",
    category: "SaaS",
    price: 79.99,
    rating: 4.9,
    reviews: 87,
    sales: 980,
    thumbnail: "/placeholder.svg?height=450&width=800&text=SaaS Platform UI",
    images: [],
    demoUrl: "",
    featured: true,
    isNew: true,
  },
  {
    id: "ecommerce-store-1",
    title: "E-Commerce Complete",
    description:
      "Full-featured e-commerce template with product listings, cart, and checkout.",
    category: "E-Commerce",
    price: 99.99,
    rating: 4.7,
    reviews: 156,
    sales: 1450,
    thumbnail: "/placeholder.svg?height=450&width=800&text=E-Commerce Complete",
    images: [],
    demoUrl: "",
    featured: true,
    isNew: false,
  },
  {
    id: "portfolio-minimal-1",
    title: "Portfolio Minimal",
    description:
      "Clean and minimal portfolio template for creatives and designers.",
    category: "Portfolio",
    price: 39.99,
    rating: 4.6,
    reviews: 92,
    sales: 870,
    thumbnail: "/placeholder.svg?height=450&width=800&text=Portfolio Minimal",
    images: [],
    demoUrl: "",
    featured: false,
    isNew: false,
  },
  {
    id: "blog-magazine-1",
    title: "Blog & Magazine",
    description:
      "Modern blog and magazine template with multiple layouts and article pages.",
    category: "Blog",
    price: 59.99,
    rating: 4.5,
    reviews: 78,
    sales: 650,
    thumbnail: "/placeholder.svg?height=450&width=800&text=Blog & Magazine",
    images: [],
    demoUrl: "",
    featured: false,
    isNew: true,
  },
  {
    id: "event-conference-1",
    title: "Event & Conference",
    description:
      "Template for events, conferences, and meetups with schedule and speaker sections.",
    category: "Events",
    price: 69.99,
    rating: 4.7,
    reviews: 64,
    sales: 520,
    thumbnail: "/placeholder.svg?height=450&width=800&text=Event & Conference",
    images: [],
    demoUrl: "",
    featured: true,
    isNew: false,
  },
  {
    id: "restaurant-cafe-1",
    title: "Restaurant & Cafe",
    description:
      "Elegant template for restaurants, cafes, and food businesses with menu and reservation features.",
    category: "Food & Beverage",
    price: 54.99,
    rating: 4.8,
    reviews: 112,
    sales: 980,
    thumbnail: "/placeholder.svg?height=450&width=800&text=Restaurant & Cafe",
    images: [],
    demoUrl: "",
    featured: false,
    isNew: false,
  },
  {
    id: "real-estate-1",
    title: "Real Estate Pro",
    description:
      "Complete real estate template with property listings, search, and agent profiles.",
    category: "Real Estate",
    price: 89.99,
    rating: 4.6,
    reviews: 95,
    sales: 760,
    thumbnail: "/placeholder.svg?height=450&width=800&text=Real Estate Pro",
    images: [],
    demoUrl: "",
    featured: false,
    isNew: true,
  },
];
